name: CI on dev

# Trigger on push or PR to dev
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Install Rust toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # 3. Install trunk
      - name: Install trunk
        run: cargo install trunk

      # 4. Build the Wasm app (detect build errors)
      - name: trunk build
        run: trunk build --release

      # 5. Run unit & integration tests
      - name: Run cargo tests
        run: cargo test --all -- --nocapture
